<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>WorldofEldara.Client</AssemblyName>
    <RootNamespace>WorldofEldara.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\WorldofEldara.Shared\WorldofEldara.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.187" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Sprites\*.eldsprite" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Sprites\*.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
